config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    resources :comments
  end
  devise_for :users
  resources :articles
  resources :reviews
  resources :products do
    get 'page/:page', action: :index, on: :collection
    resources :reviews   #Nested Route
  end

  get 'email_article/:id' => 'articles#email_article', as: 'email_article'

  get 'email_product/:id' => 'products#email_product', as: 'email_product'

  get 'store' => 'stores#index', as: 'store_index'

  get 'store/:id' => 'stores#show', as: 'store_show'

  get 'home',
      to: 'page#home',
      as: 'home'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'page/products'

  get '/products' => 'products#index', as: 'all_products'

  get 'preferences',
      to: 'page#preferences',
      as: 'preferences'

  get 'blog',
      to: 'page#blog',
      as: 'page_blog'

  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'page/articles'

  get '/articles' => 'articles#index', as: 'all_articles'

  get 'login',
      to: 'page#login',
      as: 'login'

  get '/puzzles/new' => 'puzzles#new', as: 'puzzles_new'
  post '/puzzles/create' => 'puzzles#create', as: 'puzzles_create'
  get '/puzzles/show' => 'puzzles#show', as: 'puzzles_show'

  root 'stores#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/article.rb
class Article < ApplicationRecord
  validates_presence_of :title, :author, :publish_date, :content, :thumb_image

  paginates_per 10

  after_save do |article|
    if article.published
      @users = User.where(newsletter: true).each do |user|
        UserMailer.article_email(user, article).deliver_now
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy, :email_article]
  before_action :authenticate_admin, only: [:edit, :update, :destroy, :new, :create]

  def email_article
    @users = User.all
    @users.each do |user|
      UserMailer.article_email(user, @article).deliver_now
    end
    redirect_to articles_path, notice: "Article was successfully emailed"
  end

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.page(params[:page].to_i).order(publish_date: :desc)
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def authenticate_admin
    if current_user.try( :admin? )
      return
    else
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :publish_date, :published, :content, :thumb_image)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= tinymce %>
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :publish_date %><br>
    <%= f.datetime_select :publish_date %>
  </div>

  <div class="field">
    <%= f.label :published %>
    <%= f.check_box :published %>
  </div>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content , class: "tinymce"%>
  </div>

  <div class="field">
    <%= f.label :thumb_image %> "URL"<br>
    <%= f.text_field :thumb_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Articles</h1>

<%= page_entries_info @articles %>
<div id="pag_buttons">
  <%= paginate @articles %>
</div>

<table id="styled_table">

  <thead>
  <tr>
    <% if current_user.try(:admin?) %>
        <th>Article ID</th>
    <% end %>
    <th>Title</th>
    <th>Author</th>
    <th>Publish date</th>
    <th>Published</th>
    <th>Content</th>
    <th>Thumb image</th>
    <% if current_user.try(:admin?) %>
        <th colspan="4">Show/Edit/Destroy/Email</th>
    <% else %>
        <th colspan="3">Show</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @articles.each do |article| %>
      <tr>
        <% if current_user.try(:admin?) %>
            <td><%= article.id %></td>
        <% end %>
        <td><%= truncate article.title %></td>
        <td><%= article.author %></td>
        <td><%= article.publish_date.strftime("%b %-d, %Y") %></td>
        <td><%= article.published %></td>
        <td><%= truncate(article.content.html_safe, escape: false) %></td>
        <td><%= truncate article.thumb_image %></td>
        <td><%= link_to 'Show', article %></td>
        <% if current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_article_path(article) %></td>
            <td><%= link_to 'Destroy', article, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <td><%= link_to 'Email Article', email_article_path(article) %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<br>

<div id="pag_buttons">
  <%= paginate @articles %>
</div>

<% if current_user.try(:admin?) %>
    <%= link_to 'New Article', new_article_path %>
<% end %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @article.author %>
</p>

<p>
  <strong>Publish date:</strong>
  <%= @article.publish_date.strftime("%b %-d, %Y") %>
</p>

<p>
  <strong>Published:</strong>
  <%= @article.published %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content.html_safe %>
</p>

<p>
  <strong>Thumb image:</strong>
  <%= image_tag @article.thumb_image %>
</p>

<% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_article_path(@article) %> |
<% end %>
<%= link_to 'Back', articles_path %>