config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    resources :comments
  end
  devise_for :users
  resources :articles
  resources :reviews
  resources :products do
    get 'page/:page', action: :index, on: :collection
    resources :reviews   #Nested Route
  end

  get 'email_article/:id' => 'articles#email_article', as: 'email_article'

  get 'email_product/:id' => 'products#email_product', as: 'email_product'

  get 'store' => 'stores#index', as: 'store_index'

  get 'store/:id' => 'stores#show', as: 'store_show'

  get 'home',
      to: 'page#home',
      as: 'home'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'page/products'

  get '/products' => 'products#index', as: 'all_products'

  get 'preferences',
      to: 'page#preferences',
      as: 'preferences'

  get 'blog',
      to: 'page#blog',
      as: 'page_blog'

  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'page/articles'

  get '/articles' => 'articles#index', as: 'all_articles'

  get 'login',
      to: 'page#login',
      as: 'login'

  get '/puzzles/new' => 'puzzles#new', as: 'puzzles_new'
  post '/puzzles/create' => 'puzzles#create', as: 'puzzles_create'
  get '/puzzles/show' => 'puzzles#show', as: 'puzzles_show'

  root 'stores#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  # GET /stores
  # GET /stores.json
  def index
    @products = Product.page(params[:page].to_i)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
    @product = Product.find(params[:id])
  end

end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Casey's Store</h1>

<% if current_user.try(:admin?) %>
    <td><%= link_to 'Admin\'s Products', products_path %></td><br>
<% end %>

<%= page_entries_info @products %>
<div id="pag_buttons">
  <%= paginate @products, window: 3 %>
</div>

<table id="styled_table">
  <thead>
  <tr>
    <th>Avg Rating</th>
    <th>Beer Name</th>
    <th>Beer Type</th>
    <% if current_user.try(:admin?) %>
        <th>Quantity on hand</th>
        <th>Low price range</th>
        <th>High price range</th>
        <th>Cost to company</th>
        <th>Shipping weight</th>
    <% end %>
    <th>Thumb image</th>
    <th>Full image</th>
    <% if current_user.try(:admin?) %>
        <th colspan="4">Show/Edit/Destroy/Email</th>
    <% else %>
        <th colspan="3">Show</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <% average = product.reviews.all.average(:rating) %>
      <tr>
        <td><%= (image_tag('thumbs_up.png', size: '20x20') * average).html_safe %></td>
        <td><%= truncate product.name %></td>
        <td><%= truncate(product.description.html_safe, escape: false) %></td>
        <% if current_user.try(:admin?) %>
            <td><%= product.quantity_on_hand %></td>
            <td><%= number_to_currency product.low_price_range %></td>
            <td><%= number_to_currency product.high_price_range %></td>
            <td><%= number_to_currency product.cost_to_company %></td>
            <td><%= "#{product.shipping_weight} lbs" %></td>
        <% end %>
        <td><%= truncate product.thumb_image %></td>
        <td><%= truncate product.full_image %></td>
        <td><%= link_to 'Show', store_show_path(product.id) %></td>
        <% if current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <td><%= link_to 'Email', email_product_path(product) %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<div id="pag_buttons">
  <%= paginate @products, window: 3 %>
</div>

app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>
<%= tinymce %>
<%= link_to 'Back', store_index_path %>

<br>
<% average = @product.reviews.all.average(:rating) %>
<% if !average.nil? %>
    <h5>Average Product Rating: <%= (image_tag('thumbs_up.png', size: '20x20') * average).html_safe %></h5>
<% end %>
<br>

<p>
  <strong>Beer Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Beer Type:</strong>
  <%= @product.description.html_safe %>
</p>
<% if current_user.try(:admin?) %>
    <p>
      <strong>Quantity on hand:</strong>
      <%= @product.quantity_on_hand %>
    </p>

    <p>
      <strong>Low price range:</strong>
      <%= @product.low_price_range %>
    </p>

    <p>
      <strong>High price range:</strong>
      <%= @product.high_price_range %>
    </p>

    <p>
      <strong>Cost to company:</strong>
      <%= @product.cost_to_company %>
    </p>

    <p>
      <strong>Shipping weight:</strong>
      <%= @product.shipping_weight %>
    </p>
<% end %>
<p>
  <strong>Thumb image:</strong>
  <%= image_tag @product.thumb_image %>
</p>

<p>
  <strong>Full image:</strong>
  <%= image_tag @product.full_image %>
</p>

#All Reviews
<hr>
<% @product.reviews.each do |review| %>
    <div>
      <p><%= time_ago_in_words(review.created_at) %> ago, <%= review.name %> Wrote:<br>
        <%= review.review_text.html_safe %><br>
        Rating: <%= (image_tag('thumbs_up.png', size: '20x20') * review.rating).html_safe %>
      </p>
      <% if current_user.try(:admin?) %>
          <p><%= link_to "Remove", product_review_path(@product, review), method: :delete, data: {confirm: 'Are you Sure?'} %></p>
      <% end %>
      <hr>
    </div>
<% end %>

<% if current_user.try(:admin?) %>
    #Enter a New Review
    <%= form_for([@product, @product.reviews.build]) do |f| %>

        <%= f.hidden_field :product_id %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :review_text %><br>
          <%= f.text_area :review_text, class: "tinymce" %>
        </div>

        <div class="field">
          <%= f.label :rating %><br>
          <%= f.number_field :rating %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>
<% end %>

<%= link_to 'Back', store_index_path %>