config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    resources :comments
  end
  devise_for :users
  resources :articles
  resources :reviews
  resources :products do
    get 'page/:page', action: :index, on: :collection
    resources :reviews   #Nested Route
  end

  get 'email_article/:id' => 'articles#email_article', as: 'email_article'

  get 'email_product/:id' => 'products#email_product', as: 'email_product'

  get 'store' => 'stores#index', as: 'store_index'

  get 'store/:id' => 'stores#show', as: 'store_show'

  get 'home',
      to: 'page#home',
      as: 'home'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'page/products'

  get '/products' => 'products#index', as: 'all_products'

  get 'preferences',
      to: 'page#preferences',
      as: 'preferences'

  get 'blog',
      to: 'page#blog',
      as: 'page_blog'

  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'page/articles'

  get '/articles' => 'articles#index', as: 'all_articles'

  get 'login',
      to: 'page#login',
      as: 'login'

  get '/puzzles/new' => 'puzzles#new', as: 'puzzles_new'
  post '/puzzles/create' => 'puzzles#create', as: 'puzzles_create'
  get '/puzzles/show' => 'puzzles#show', as: 'puzzles_show'

  root 'stores#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/views/shared/_nav.html.erb
<% if user_signed_in? %>
    <p><%= current_user.email %></p>
<% end %>

<nav class="pull-left">
  <ul class="list-unstyled">
    <li class="animated wow fadeInLeft" data-wow-delay=".2s"><%= link_to "Products", root_path %></li>
    <li class="animated wow fadeInLeft" data-wow-delay=".6s"><%= link_to "Articles", all_articles_path %></li>
    <li class="animated wow fadeInLeft" data-wow-delay=".4s"><%= link_to "Blog", blogs_path %></li>
    <li class="animated wow fadeInLeft" data-wow-delay=".1s"><%= link_to "Contact Us", contact_us_path %></li>
    <li class="animated wow fadeInLeft" data-wow-delay=".5s"><%= link_to "Calendar", calendar_path %></li>
    <% if user_signed_in? %>
        <li class="animated wow fadeInLeft" data-wow-delay="0s"><%= link_to "Preferences", edit_user_registration_path %></li>
        <li><%= link_to "Log Out", destroy_user_session_path, :method => :delete %></li>
    <% else %>
        <li><%= link_to "Log In", new_user_session_path %></li>
    <% end %>
    <li><%= link_to "Register", new_user_registration_path %></li>
  </ul>
</nav>
<span class="burger_icon">menu</span>