config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :blogs do
    resources :comments
  end
  devise_for :users
  resources :articles
  resources :reviews
  resources :products do
    get 'page/:page', action: :index, on: :collection
    resources :reviews   #Nested Route
  end

  get 'email_article/:id' => 'articles#email_article', as: 'email_article'

  get 'email_product/:id' => 'products#email_product', as: 'email_product'

  get 'store' => 'stores#index', as: 'store_index'

  get 'store/:id' => 'stores#show', as: 'store_show'

  get 'home',
      to: 'page#home',
      as: 'home'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'page/products'

  get '/products' => 'products#index', as: 'all_products'

  get 'preferences',
      to: 'page#preferences',
      as: 'preferences'

  get 'blog',
      to: 'page#blog',
      as: 'page_blog'

  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'page/articles'

  get '/articles' => 'articles#index', as: 'all_articles'

  get 'login',
      to: 'page#login',
      as: 'login'

  get '/puzzles/new' => 'puzzles#new', as: 'puzzles_new'
  post '/puzzles/create' => 'puzzles#create', as: 'puzzles_create'
  get '/puzzles/show' => 'puzzles#show', as: 'puzzles_show'

  root 'stores#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates_presence_of :name, :description, :thumb_image, :full_image
  validates_numericality_of :quantity_on_hand
  validates_numericality_of :low_price_range, :cost_to_company, :shipping_weight, :greater_than => 0.01
  validates_numericality_of :high_price_range, :less_than => 100000000.00

  paginates_per 10

  after_save do | product |
    @users = User.where(newsletter: true).each do | user |
      UserMailer.product_email(user, product).deliver_now
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :email_product]
  before_action :authenticate_user!
  before_action :authenticate_admin, only: [:edit, :update, :destroy, :new, :create]

  def email_product
    @users = User.where(newsletter: true)
    @users.each do |user|
      UserMailer.product_email(user, @product).deliver_now
    end
    redirect_to products_path, notice: "Product was successfully emailed"
  end

  # GET /products
  # GET /products.json
  def index
    @products = Product.page(params[:page].to_i)
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :quantity_on_hand, :low_price_range, :high_price_range, :cost_to_company, :shipping_weight, :thumb_image, :full_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= tinymce %>
<%= form_for(product) do |f| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, id: :product_name %>
  </div>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description, id: :product_description , class: "tinymce"%>
  </div>

  <div class="field">
    <%= f.label :quantity_on_hand %>
    <%= f.number_field :quantity_on_hand, id: :product_quantity_on_hand %>
  </div>

  <div class="field">
    <%= f.label :low_price_range %>
    <%= f.text_field :low_price_range, id: :product_low_price_range %>
  </div>

  <div class="field">
    <%= f.label :high_price_range %>
    <%= f.text_field :high_price_range, id: :product_high_price_range %>
  </div>

  <div class="field">
    <%= f.label :cost_to_company %>
    <%= f.text_field :cost_to_company, id: :product_cost_to_company %>
  </div>

  <div class="field">
    <%= f.label :shipping_weight %>
    <%= f.text_field :shipping_weight, id: :product_shipping_weight %>
  </div>

  <div class="field">
    <%= f.label :thumb_image %>
    <%= f.text_field :thumb_image, id: :product_thumb_image %>
  </div>

  <div class="field">
    <%= f.label :full_image %>
    <%= f.text_field :full_image, id: :product_full_image %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="title">Products</h1>

<%= page_entries_info @products %>
<div id="pag_buttons">
  <%= paginate @products, window: 3 %>
</div>

<table id="styled_table">
  <thead>
  <tr>
    <% if current_user.try(:admin?) %>
        <th>ID</th>
    <% end %>
    <th>Beer Name</th>
    <th>Beer Type</th>
    <% if current_user.try(:admin?) %>
        <th>Quantity on hand</th>
        <th>Low price range</th>
        <th>High price range</th>
        <th>Cost to company</th>
        <th>Shipping weight</th>
    <% end %>
    <th>Thumb image</th>
    <th>Full image</th>
    <% if current_user.try(:admin?) %>
        <th colspan="4">Show/Edit/Destroy/Email</th>
    <% else %>
        <th colspan="3">Show</th>
    <% end %>
  </tr>
  </thead>

  <tbody>
  <% @products.each do |product| %>
      <tr>
        <% if current_user.try(:admin?) %>
            <td><%= product.id %></td>
        <% end %>
        <td><%= truncate product.name %></td>
        <td><%= truncate(product.description.html_safe, escape: false) %></td>
        <% if current_user.try(:admin?) %>
            <td><%= product.quantity_on_hand %></td>
            <td><%= number_to_currency product.low_price_range %></td>
            <td><%= number_to_currency product.high_price_range %></td>
            <td><%= number_to_currency product.cost_to_company %></td>
            <td><%= "#{product.shipping_weight} lbs" %></td>
        <% end %>
        <td><%= truncate product.thumb_image %></td>
        <td><%= truncate product.full_image %></td>
        <td><%= link_to 'Show', product %></td>
        <% if current_user.try(:admin?) %>
            <td><%= link_to 'Edit', edit_product_path(product) %></td>
            <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
            <td><%= link_to 'Email', email_product_path(product) %></td>
        <% end %>
      </tr>
  <% end %>
  </tbody>
</table>
<br>
<div id="pag_buttons">
  <%= paginate @products, window: 3 %>
</div>

<% if current_user.try(:admin?) %>
    <%= link_to 'New Product', new_product_path %>
<% end %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<%= tinymce %>
<% if current_user.try(:admin?) %>
    <%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', products_path %>

<br>
<% average = @product.reviews.all.average(:rating) %>
<% if !average.nil? %>
    <h5>Average Product Rating: <%= (image_tag('thumbs_up.png', size: '20x20') * average).html_safe %></h5>
<% end %>
<br>

<p>
  <strong>Beer Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Beer Type:</strong>
  <%= @product.description.html_safe %>
</p>
<% if current_user.try(:admin?) %>
    <p>
      <strong>Quantity on hand:</strong>
      <%= @product.quantity_on_hand %>
    </p>

    <p>
      <strong>Low price range:</strong>
      <%= number_to_currency @product.low_price_range %>
    </p>

    <p>
      <strong>High price range:</strong>
      <%= number_to_currency @product.high_price_range %>
    </p>

    <p>
      <strong>Cost to company:</strong>
      <%= number_to_currency @product.cost_to_company %>
    </p>

    <p>
      <strong>Shipping weight:</strong>
      <%= "#{@product.shipping_weight} lbs" %>
    </p>
<% end %>
<p>
  <strong>Thumb image:</strong>
  <%= image_tag @product.thumb_image %>
</p>

<p>
  <strong>Full image:</strong>
  <%= image_tag @product.full_image %>
</p>

#All Reviews
<hr>
<% @product.reviews.each do |review| %>
    <div>
      <p><%= time_ago_in_words(review.created_at) %> ago, <%= review.name %> Wrote:<br>
        <%= review.review_text.html_safe %><br>
        Rating: <%= (image_tag('thumbs_up.png', size: '20x20') * review.rating).html_safe %>
      </p>
      <% if current_user.try(:admin?) %>
          <p><%= link_to "Remove", product_review_path(@product, review), method: :delete, data: {confirm: 'Are you Sure?'} %></p>
      <% end %>
      <hr>
    </div>
<% end %>

<% if current_user.try(:admin?) %>
    #Enter a New Review
    <%= form_for([@product, @product.reviews.build]) do |f| %>

        <%= f.hidden_field :product_id %>

        <div class="field">
          <%= f.label :name %><br>
          <%= f.text_field :name %>
        </div>

        <div class="field">
          <%= f.label :review_text %><br>
          <%= f.text_area :review_text, class: "tinymce" %>
        </div>

        <div class="field">
          <%= f.label :rating %><br>
          <%= f.number_field :rating %>
        </div>

        <div class="actions">
          <%= f.submit %>
        </div>
    <% end %>

    <%= link_to 'Edit', edit_product_path(@product) %> |
<% end %>
<%= link_to 'Back', products_path %>